### ISSUE TITLE
Translation formatting

### ISSUE THREAD

**Issue by Migilian** [probablykory/valheim-mods#1]
Now it's not very convenient to see just one really long line of keys and their translations, so, I think, it would be much more convenient having it more vertical, something like:
key = translation,
key = translation,
etc.

Ofc, there's not so much to translate, so it's not something crucial to have, but it would've been a nice little touch indeed.

**Comment by probablykory** [comment]
The next version will add linebreaks to the default translation files.

**Comment by probablykory** [comment]
Fixed in 1.2.3.  Default translations ship preformatted.
