### ISSUE TITLE
hello. I'd like to add a translation...

### ISSUE THREAD

**Issue by So1207** [probablykory/valheim-mods#4]
I am a Valheim gamer in Korea. Thanks for the awesome mod.
I made a Korean translation for the 'MoreCrossbows' mod...there were good instructions on your page. thank you
You can inspect it and make as many changes as you want. It would be nice if a Korean translation was added...

[Korean.json](https://github.com/probablykory/valheim-mods/files/14826508/Korean.json)

**Comment by probablykory** [comment]
Hi there.  Thank you for the translation!  Ill make sure to include it in the next release 🙂

**Comment by probablykory** [comment]
Released with 1.2.9. Thanks again.
