### ISSUE TITLE
Error during startup modload MoreCrossbows version 1.2.8

### ISSUE THREAD

**Issue by SissyTrashQueen** [probablykory/valheim-mods#5]
Log INFO:

![image](https://github.com/probablykory/valheim-mods/assets/55768134/e84e60b1-3cb5-4c1a-ae2f-4e4023ea85c1)

**Comment by probablykory** [comment]
Can you please attach your <game>\BepInEx\LogOutput.log that contains this error?  It will tell me more information about what's happening, what other mods are running, etc.

I've just tested it on my machine and it runs fine.

Thanks.

**Comment by probablykory** [comment]
I still cannot replicate, tried with 1.2.8 and the newly released 1.2.9.  Closing, but feel free to reopen if you have a log.
