### ISSUE TITLE
Craftstations names

### ISSUE THREAD

**Issue by f4r5454** [probablykory/valheim-mods#7]
I can't achieve to add a jewel craftable in forge using your mod MoreJewelry

Log says : "Custom crafting station 'Forge' does not exist" whereas i wrote 'forge' in the yml file (without quotes).

Thank you for your much appreciated work anyway.

**Comment by probablykory** [comment]
Thanks for the report, I'll take a look at this when I can.

**Comment by probablykory** [comment]
This should now be fixed in 1.0.9.  Sorry for the delay 🙂
