### ISSUE TITLE
[BUG] MoreCrossbows - All crossbows and modded bolts gone from inventory after latest update.

### ISSUE THREAD

**Issue by Audrey-Orpean-Hossain** [probablykory/valheim-mods#9]
Details:
Valheim Version:
Mod Version:
Jotunn Version(if applicable):
Repeatability: Consistent

**Problem Description:**
All of my modded crossbows are gone, along with the modded bolts.

**Expected Behaviour:**
Modded Crossbows to exist.

**Actual Behaviour:**
Doesn't exist, gone.

**Link to your server's and client's LogOutput.log**
https://pastebin.com/gQ6t7ZXP

**Comment by probablykory** [comment]
Thank you for the bug report (and the log!).  Please find the newest MoreCrossbows v1.2.11 on [thunderstore](https://thunderstore.io/c/valheim/p/probablykory/MoreCrossbows), which is now updated for Bog Witch.
